export const STUDENTS = [
    { id: 1, name: "Aleksandar", image: " ", active: true },
    { id: 2, name: "Bettina", image: " ", active: true },
    { id: 3, name: "Catalina", image: " ", active: true },
    { id: 4, name: "Christiane", image: " ", active: true },
    { id: 5, name: "Jeremy", image: " ", active: true },
    { id: 6, name: "Milivoje", image: " ", active: true },
    { id: 7, name: "Vanessa", image: " ", active: true },
    { id: 8, name: "Anamaria", icon: " ", active: true },
    { id: 9, name: "Balint", image: " ", active: true },
    { id: 10, name: "Eri", image: " ", active: true },
    { id: 11, name: "Gojart", image: " ", active: true },
    { id: 12, name: "Hadar", image: " ", active: true },
    { id: 13, name: "Jovana", image: " ", active: true },
    { id: 14, name: "Lea", image: " ", active: true },
    { id: 15, name: "Eva", image: " ", active: true },
    { id: 16, name: "Ruba",image: " ", active: true },
    { id: 17, name: "Shabnaz",image: " ", active: true },
    { id: 18, name: "Teofil", image: " ", active: true }
  ];